### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 404forever1** [AdamMekush/WatutPlugin#1]
[19:16:49 INFO]: [watut] Enabling watut v1.0.0
[19:16:49 ERROR]: Error occurred while enabling watut v1.0.0 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:524) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:228) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:210) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at org.bukkit.scheduler.BukkitRunnable.runTaskTimer(BukkitRunnable.java:117) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at watut-bukkit-1.0.0.jar/me.slide.watut.WatutPlugin.onEnable(WatutPlugin.java:29) ~[watut-bukkit-1.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:331) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[luminol-1.21.1.jar:1.21.1-DEV-dacd3c5]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by SlidePowered** [comment]
Try updated plugin on Modrinth :)

**Comment by 404forever1** [comment]
> Try updated plugin on Modrinth :)

Is it possible to set the leave and join message not to be displayed?

**Comment by 404forever1** [comment]
> > Try updated plugin on Modrinth :)
> 
> Is it possible to set the leave and join message not to be displayed?

afk

**Comment by SlidePowered** [comment]
> > Try updated plugin on Modrinth :)
> 
> Is it possible to set the leave and join message not to be displayed?

Of course! Just set idle.broadcast.enabled to false

**Comment by 404forever1** [comment]
FOLIA ALSO CANT WORK

**Comment by SlidePowered** [comment]
> FOLIA ALSO CANT WORK

Currently, WatutPlugin doesn't provide Folia support(you can see it on Modrinth plugin page), but it's planned for the future updates.
